### ISSUE TITLE
service [postgres] setup failed error

### ISSUE THREAD

**Issue by asharabu** [weaponry/pgscv#5]
Hi,
I am trying to implement pgscv exporter in  one of the PostgreSQL databases but we are getting the below error on pgscv docker container log, 

> 
{"level":"info","service":"pgscv","time":"2021-07-01T11:30:00Z","message":"*** IMPORTANT ***: pgSCV by default collects information about user queries. Tracking queries can be disabled with 'no_track_mode: true' in config file."}
{"level":"info","service":"pgscv","time":"2021-07-01T11:30:00Z","message":"no-track mode disabled"}
{"level":"info","service":"pgscv","time":"2021-07-01T11:30:00Z","message":"registered new service [system:0]"}
{"level":"info","service":"pgscv","time":"2021-07-01T11:30:00Z","message":"registered new service [postgres]"}
**{"level":"error","service":"pgscv","time":"2021-07-01T11:30:00Z","message":"service [postgres] setup failed: no rows in result set; skip"}**
{"level":"info","service":"pgscv","time":"2021-07-01T11:30:00Z","message":"accepting requests on 0.0.0.0:9890"}
>

**Comment by mastergenius** [comment]
In our case query SELECT setting FROM pg_settings WHERE name = 'data_directory' didn't return any rows
