### ISSUE TITLE
Unable to see some metrics in grafana

### ISSUE THREAD

**Issue by asharabu** [weaponry/pgscv#6]
Hi,
I am unable to get some metrics like statements, errors, response time in grafana, showing as No data.  I  used the grafana [dashboard ](https://grafana.com/grafana/dashboards/14540)

![image](https://user-images.githubusercontent.com/42669995/124420048-5bc12580-dd7c-11eb-8e0c-9f554153df22.png)

**Comment by lesovsky** [comment]
Make sure you have:
1. installed and enabled [pg_stat_statements](https://www.postgresql.org/docs/current/pgstatstatements.html).
2. properly configured logging (logging_collector = on, non-empty log_directory and log_filename) - pgSCV also have to be installed on the same host with Postgres for collecting log metrics.
